import { Phone, Sale, Return, BackupData, Credit, CreditPayment } from '@/types';
import { phoneDB } from '@/lib/db-supabase';

const BACKUP_VERSION = '1.0.0';

/**
 * Export all data to a JSON backup file
 */
export async function exportBackup(): Promise<void> {
  try {
    const [phones, sales, returns, credits, creditPayments] = await Promise.all([
      phoneDB.getAllPhones(),
      phoneDB.getAllSales(),
      phoneDB.getAllReturns(),
      phoneDB.getAllCredits(),
      phoneDB.getAllCreditPayments(),
    ]);

    const backupData: BackupData = {
      phones,
      sales,
      returns,
      credits,
      creditPayments,
      exportDate: new Date().toISOString(),
      version: BACKUP_VERSION,
    };

    const jsonString = JSON.stringify(backupData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    
    const timestamp = new Date().toISOString().split('T')[0].replace(/-/g, '');
    link.setAttribute('href', url);
    link.setAttribute('download', `iphone-pos-backup-${timestamp}.json`);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error exporting backup:', error);
    throw new Error('Failed to export backup');
  }
}

/**
 * Import data from a JSON backup file
 */
export async function importBackup(file: File): Promise<{ success: boolean; message: string }> {
  try {
    const text = await file.text();
    const backupData: BackupData = JSON.parse(text);

    // Validate backup data structure
    if (!backupData.phones || !backupData.sales || !backupData.returns) {
      return {
        success: false,
        message: 'Invalid backup file format. Missing required data.',
      };
    }

    // Import credits if they exist (for backward compatibility)
    if (backupData.credits && backupData.credits.length > 0) {
      for (const credit of backupData.credits) {
        const { id, ...creditData } = credit;
        await phoneDB.addCredit(creditData);
      }
    }

    // Import credit payments if they exist
    if (backupData.creditPayments && backupData.creditPayments.length > 0) {
      for (const payment of backupData.creditPayments) {
        const { id, ...paymentData } = payment;
        // Use recordCreditPayment if available, otherwise skip (payments are usually created through the app)
        // For now, we'll skip importing payments as they should be recreated through the app
        console.log('Skipping credit payment import - payments should be recorded through the app');
      }
    }

    // Validate version (optional - for future compatibility)
    if (backupData.version && backupData.version !== BACKUP_VERSION) {
      console.warn(`Backup version ${backupData.version} differs from current version ${BACKUP_VERSION}`);
    }

    // Clear existing data
    await phoneDB.clearAllData();

    // Import phones (IDs will be auto-generated by Supabase)
    for (const phone of backupData.phones) {
      const { id, ...phoneData } = phone;
      await phoneDB.addPhone(phoneData);
    }

    // Import sales (IDs will be auto-generated by Supabase)
    for (const sale of backupData.sales) {
      const { id, ...saleData } = sale;
      await phoneDB.addSale(saleData);
    }

    // Import returns (IDs will be auto-generated by Supabase)
    for (const returnData of backupData.returns) {
      const { id, ...returnItem } = returnData;
      await phoneDB.addReturn(returnItem);
    }

    const creditsCount = backupData.credits?.length || 0;
    const paymentsCount = backupData.creditPayments?.length || 0;
    const creditsMsg = creditsCount > 0 ? `, ${creditsCount} credits` : '';
    const paymentsMsg = paymentsCount > 0 ? `, and ${paymentsCount} payments` : '';
    return {
      success: true,
      message: `Successfully imported ${backupData.phones.length} phones, ${backupData.sales.length} sales, ${backupData.returns.length} returns${creditsMsg}${paymentsMsg}.`,
    };
  } catch (error) {
    console.error('Error importing backup:', error);
    if (error instanceof SyntaxError) {
      return {
        success: false,
        message: 'Invalid JSON file. Please check the file format.',
      };
    }
    return {
      success: false,
      message: 'Failed to import backup. Please try again.',
    };
  }
}

